
# This is a Terragrunt module generated by boilerplate.
terraform {
#  source = "git::https://github.com/nikrat25/test//datafactory?ref=main&shallow=true"
#  source = "../../../../config/resources/datafactory"
   source = "."
}

# terraform {
#  source = "git@github.com:nikrat25/test.git//datafactory?ref=main"
  
  # Modern approach - use upgrade flag if needed
#  extra_arguments "init_args" {
#    commands = ["init"]
#    arguments = [
#      "-upgrade"
#    ]
# }
# }

# Configure a shorter download directory
# download_dir = "C:/tf-cache/${path_relative_to_include()}"

#source = "../../../config/resources/datafactory"
inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  type = "{{.type}}"

  adf_name = "{{.adf_name}}"

  git_should_apply_vsts_config = "{{.git_should_apply_vsts_config}}"

  private_subnet_name  = "{{.private_subnet_name}}"

  gitProjectName = "{{.gitProjectName}}"

  gitAccountName = "{{.gitAccountName}}"

  gitRepositoryName = "{{.gitRepositoryName}}"

  gitBranchName = "{{.gitBranchName}}"

  gitADFRootFolder = "{{.gitADFRootFolder}}"

  gitRepositoryURL = "{{.gitRepositoryURL}}"

  managed_virtual_network_enabled = "{{.managed_virtual_network_enabled}}"

  public_network_enabled = "{{.public_network_enabled}}"

  private_endpoint_name = "{{.private_endpoint_name}}"

  private_service_connection_name = "{{.private_service_connection_name}}"

  tenant_id = "{{.tenant_id}}"

  client_id = "{{.client_id}}"

  client_secret = "{{.client_secret}}"

  subscription_id = "{{.subscription_id}}"

 # adf_managed_pe_integrations = "{{.adf_managed_pe_integrations}}"

  # Description: Name of SNet 1. This should be provided by the root main.tf, collected from the PLTMGT outputs.
  # Type: string
  private_subnet_name = "{{.private_subnet_name}}"


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Azure Devops git integration is required
  # Type: bool
  # gitShouldApplyVSTSConfig = false

  # Description: Github git integration is required
  # Type: bool
  # gitShouldApplyGithubConfig = false

  # Description: The project name where the Git Repos is for ADF. Will default to the solution name
  # Type: string
  # gitProjectName = ""

  # Description: Name of the Devops Account
  # Type: string
  # gitAccountName = "marsanalytics"

  # Description: Name of the Devops Git Repos where the ADF code is created, if not provided then defaults to the solutionname
  # Type: string
  gitRepositoryName = "{{.gitRepositoryName}}"

  # Description: Name of the git collaboration branch for datafactory
  # Type: string
  gitBranchName = "{{.gitBranchName}}"

  # Description: The root folder within the repos where you want Data Factory to save the source files
  # Type: string
  gitADFRootFolder = "{{.gitADFRootFolder}}"

  # Description: Github URL for the configuration for Data Factory
  # Type: string
  # gitRepositoryURL = "https://github.com"

  # Description: Is Managed Virtual Network enabled
  # Type: bool
  {{if .managed_virtual_network_enabled}}
  managed_virtual_network_enabled = true
  {{else}}
  managed_virtual_network_enabled = false
  {{end}}

  # Description: Is public network enabled for ADF
  # Type: bool
  {{if .public_network_enabled}}
  public_network_enabled = true
  {{else}}
  # public_network_enabled = false
  {{end}}

  # Description: Private endpoint name for this container registry
  # Type: string
  # private_endpoint_name = ""

  # Description: Private service connection name for this container registry
  # Type: string
  # private_service_connection_name = ""

  # Description: (variable adf_managed_pe_integrations did not define a description)
  # Type: map
  {{if .adf_managed_pe_integrations}}
  # adf_managed_pe_integrations = {{.adf_managed_pe_integrations}}
  {{else}}
  # adf_managed_pe_integrations = {}
  {{end}}
}












