
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "../../../config/resources/datafactory"
}


inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------


  # Description: Name of SNet 1. This should be provided by the root main.tf, collected from the PLTMGT outputs.
  # Type: string
  private_subnet_name = "{{.private_subnet_name}}"


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Azure Devops git integration is required
  # Type: bool
  # gitShouldApplyVSTSConfig = false

  # Description: Github git integration is required
  # Type: bool
  # gitShouldApplyGithubConfig = false

  # Description: The project name where the Git Repos is for ADF. Will default to the solution name
  # Type: string
  # gitProjectName = ""

  # Description: Name of the Devops Account
  # Type: string
  # gitAccountName = "marsanalytics"

  # Description: Name of the Devops Git Repos where the ADF code is created, if not provided then defaults to the solutionname
  # Type: string
  gitRepositoryName = "{{.gitRepositoryName}}"

  # Description: Name of the git collaboration branch for datafactory
  # Type: string
  gitBranchName = "{{.gitBranchName}}"

  # Description: The root folder within the repos where you want Data Factory to save the source files
  # Type: string
  gitADFRootFolder = "{{.gitADFRootFolder}}"

  # Description: Github URL for the configuration for Data Factory
  # Type: string
  # gitRepositoryURL = "https://github.com"

  # Description: Is Managed Virtual Network enabled
  # Type: bool
  {{if .managed_virtual_network_enabled}}
  managed_virtual_network_enabled = true
  {{else}}
  managed_virtual_network_enabled = false
  {{end}}

  # Description: Is public network enabled for ADF
  # Type: bool
  {{if .public_network_enabled}}
  public_network_enabled = true
  {{else}}
  # public_network_enabled = false
  {{end}}

  # Description: Private endpoint name for this container registry
  # Type: string
  # private_endpoint_name = ""

  # Description: Private service connection name for this container registry
  # Type: string
  # private_service_connection_name = ""

  # Description: (variable adf_managed_pe_integrations did not define a description)
  # Type: map
  {{if .adf_managed_pe_integrations}}
  adf_managed_pe_integrations = {{.adf_managed_pe_integrations}}
  {{else}}
  # adf_managed_pe_integrations = {}
  {{end}}
}
