# This is a Terragrunt module generated by boilerplate.
terraform {
   source = "."
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  type = "{{.type}}"


  integration_runtime_name = "{{.integration_runtime_name}}"

  usecase_name = "{{.usecase_name}}"

  git_account_name = "{{.git_account_name}}"

  git_repository_name = "{{.git_repository_name}}"

  git_branch_name = "{{.git_branch_name}}"

  git_repository_url = "{{.git_repository_url}}"

  private_subnet_name = "{{.private_subnet_name}}"

}




















