
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "${path_relative_from_include()}/modules/local/entra_lookup"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: (variable user_mails did not define a description)
  # Type: list
  #   user_mails = []

  # Description: (variable group_names did not define a description)
  # Type: list
  # group_names = []

  # Description: (variable sp_name did not define a description)
  # Type: list
  # sp_name = []
}
