# This is a Terragrunt module generated by boilerplate.
# TODO: there is no version for adf-ir, using adf version
terraform {
  source = "${include.envcommon.locals.base_source_url_github}/datafactory//datafactory_integration_runtime?ref=${include.envcommon.locals.datafactory_version}"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

include "envcommon" {
  path   = "${dirname(find_in_parent_folders("root.hcl"))}/_envcommon/pdap.hcl"
  expose = true
}

dependency "entra_lookup" {
  config_path = "../entra_lookup"
}

dependency "lookup" {
  config_path = "../../../lookup"
}

dependency "product" {
  config_path = "../product"
}

dependency "solutionsettings" {
  config_path = "../solutionsettings"
}

dependency "solutionsettings" {
  config_path = "../../datafactory"
}

dependencies "resource_group" {
  paths = "../resource_group"
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: (variable solution_settings did not define a description)
  # Type: any
  solution_settings = dependency.solutionsettings.outputs.settings

  # Description: (variable tags did not define a description)
  # Type: map
  tags = dependency.solutionsettings.outputs.tags

  # Description: Resource group name for this module
  # Type: string
  resource_group_name = dependency.solutionsettings.outputs.settings["resource_group_name"]

  # Description: Name of Azure Data Factory instance
  # Type: string
  azurerm_data_factory_name = dependency.datafactory.outputs.name

  # Description: Integration runtime suffix name
  # Type: string
  {{if .integration_runtime_suffix}}
  integration_runtime_suffix = "{{.integration_runtime_suffix}}"
  {{else}}
  integration_runtime_suffix = "ir"
  {{end}}

  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Integration runtime number
  # Type: string
  {{if .integration_runtime_no}}
  integration_runtime_no = "{{.integration_runtime_no}}"
  {{else}}
  # integration_runtime_no = "001"
  {{end}}
}