
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "${include.envcommon.locals.base_source_url_github}//datafactory?ref=${include.envcommon.locals.datafactory_version}"
}



inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  contributer = "{{.contributer}}"

  type = "{{.type}}"

  existing_adf_name = "{{.existing_adf_name}}"

  security_group_member_de = "{{.security_group_member_de}}"

  datafactory_contributer = "{{.datafactory_contributer}}"

  
}
