
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "${include.envcommon.locals.base_source_url_github}//datafactory?ref=${include.envcommon.locals.datafactory_version}"
}



inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

 Datafactory Type = "{{.type}}"
}
