
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "${include.envcommon.locals.base_source_url_azdo}//modules/azuredevops?ref=devops_repo-v1.0.0"
}

include "root" {
  path = find_in_parent_folders("terragrunt.hcl")
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: The name of the Azure DevOps project.
  # Type: string
  project_name = "{{.project_name}}" # TODO: fill in value

  # Description: The access level or group name for the new Azure DevOps Team
  # Type: string
  project_group_name = "{{.project_group_name}}" # TODO: fill in value

  # Description: The name of the Azure DevOps team.
  # Type: string
  team_name = "{{.team_name}}" # TODO: fill in value

  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: A list of Azure AD groups whose members will be added to the team. The key is the group name.
  # Type: list
  if {{.azuread_group_members}}
  azuread_group_members = {{.azuread_group_members}}
  {{else}}
  # azuread_group_members = []
  {{end}}

  # Description: A list of Azure AD groups whose admins will be added to the team as admin. The key is the group name.
  # Type: list
  if {{.azuread_group_admins}}
  azuread_group_admins = {{.azuread_group_admins}}
  {{else}}
  # azuread_group_admins = []
  {{end}}


  # Description: A list repositories to be created in the project.
  # Type: list
  {{if .repository_names}}
  repository_names = {{.repository_names}}
  {{else}}
  # repository_names = []
  {{end}}

  # Description: If Devops Repo admin needed
  # Type: bool
  # admin_required = false

  # Description: (Optional) This is used to assign specific permission at the repo level to DevOps admin group
  # Type: map
  # permissions = {}

}
