
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "../../../config/resources/app_service"
}



inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  type = "{{.type}}"
}
