
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "../../../config/resources/key_vault"
}


inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------


  type = "{{.type}}"

  akv_subnet = "{{.akv_subnet}}"

  key_vault_reader_role = "{{.key_vault_reader_role}}"
}
