
# This is a Terragrunt module generated by boilerplate.
# terraform {
#  source = "../../../config/resources/key_vault"
# }
terraform {
  source = "git@github.com:nikrat25/test.git//resources/key_vault?ref=main"
  
  extra_arguments "init_args" {
    commands = ["init"]
    arguments = [
      "-upgrade"
    ]
  }
}

# Configure a shorter download directory
download_dir = "C:/tf-cache/${path_relative_to_include()}"

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  key_vault_name = "{{.key_vault_name}}"

  type = "{{.type}}"

  akv_subnet = "{{.akv_subnet}}"

  key_vault_reader_role = "{{.key_vault_reader_role}}"
 
  tenant_id = "{{.tenant_id}}"

  client_id = "{{.client_id}}"

  client_secret = "{{.client_secret}}"

  subscription_id = "{{.subscription_id}}"
