
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "${include.envcommon.locals.base_source_url_github}//solutionsettings?ref=${include.envcommon.locals.solutionsettings_version}"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

include "envcommon" {
  path   = "${dirname(find_in_parent_folders("root.hcl"))}/_envcommon/pdap.hcl"
  expose = true
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Solution name
  # Type: string
  solution_name = include.root.locals.product

  # Description: (variable location did not define a description)
  # Type: string
  location = include.root.locals.region_long

  # Description: (variable resource_group_name did not define a description)
  # Type: string
  resource_group_name = upper("${include.root.locals.banner}-${include.root.locals.product}-${include.root.locals.region}-${include.root.locals.environment}-RG")


  # Description: Environment
  # Type: string
  environment = include.root.locals.environment

  # Description: a dictionary (map) of tags to propagate
  # Type: map
  tags = {{.tags}}

  # Description: Name of the virtual network
  # Type: string
  // vnet_name = ""

  # Description: Name of the resource group where the virtual network resides
  # Type: string
  // vnet_rg = ""


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: (variable core_resource_group_name did not define a description)
  # Type: string
  # core_resource_group_name = "DNA-CORE-HUB-EUS2-RG"

  # Description: Azure Devops tenant Id
  # Type: string
  # devops_tenant_id = "2fc13e34-f03f-498b-982a-7cb446e25bc6"

}
