
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "../../../config/resources/existing_key_vault"
}


inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------


 type = "{{.type}}"

}
