
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "../../../config/resources/existing_key_vault"
}


inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------
existing_key_vault_name = "{{.existing_key_vault_name}}"

 type = "{{.type}}"

}
