
# This is a Terragrunt module generated by boilerplate.
terraform {
   source = "."
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  type = "{{.type}}"

  azuread_group_name = "{{.azuread_group_name}}"

}















