
# This is a Terragrunt module generated by boilerplate.
terraform {
   source = "."
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  type = "{{.type}}"
  security_group_members_de = "{{.security_group_members_de}}"
}















